### ISSUE TITLE
Add the standalone SFTP server into this daemon

### ISSUE THREAD

**Issue by ZeProf2Code** [pterodactyl/wings#11]

**Comment by Lunaversitay** [comment]
The daemon isn't even fully finished, you should wait until its actually finished before requesting features to be added.

**Comment by ZeProf2Code** [comment]
Other issues here are features requests too

**Comment by Sir3lit** [comment]
This has already been addressed by Dane in the dev chat, and he said it will be separate for now.

**Comment by DaneEveritt** [comment]
Please stop creating issues and PRs in this repo. It specifically says this is still under heavy development. I am well aware that things are missing, creating issues about it does nothing to help that.
