### ISSUE TITLE
Support Casbin as the authorization backend

### ISSUE THREAD

**Issue by hsluoyz** [Pterodactyl/wings#2]
Hi, [Casbin](https://github.com/casbin/casbin) is an authorization library that supports models like ACL, RBAC, ABAC.

Related to RBAC, Casbin has several advantages:
1. roles can be cascaded, aka roles can have roles.
2. support resource roles, so users have their roles and resource have their roles too. role = group here.
3. the permission assignments (or policy in Casbin's language) can be persisted in files or database (Gorm or Xorm or any popular DBs).

And you can even customize your own access control model, for example, mix RBAC and ABAC together by using roles and attributes at the same time. It's very flexible.

Casbin can provide more flexibility and security than the current permission system. Let me know if there's any question:) Thanks.

**Comment by schrej** [comment]
Hi, thank you for suggesting. We are planning on rewriting our authentication/authorization system with this new daemon. As we are not using any of the models your framework supports yet and they don't really suit our needs and are probably rather overkill for our uses. Even though we thought about enabling wings to be used without our panel this is not our main focus at the moment as we have more important things on our todo list, I'm therefore closing this issue.
