### ISSUE TITLE
When the last update comes i get everytime this error

### ISSUE THREAD

**Issue by SocialHype** [pterodactyl/wings#4]
Everthing is installed correctly in the prev version everythings works but with the newest verstion from the panel the minecraft spigot doesnt work any more i have installed java and everything
![image](https://user-images.githubusercontent.com/38562536/39068179-a4d5715a-44db-11e8-8033-ddee21d1e5ff.png)

**Comment by SocialHype** [comment]
https://pastebin.com/R3ZtpuQZ

**Comment by parkervcp** [comment]
This is not a wings issue either.

**Comment by SocialHype** [comment]
i knowwwwww but i cannot write on the daemon.;///

**Comment by parkervcp** [comment]
It's not a daemon issue either. As I have commented on your other issue you opened.

**Comment by SocialHype** [comment]
everyone is deniening it i send it on the panel thing and now here

**Comment by SocialHype** [comment]
and on the discord someone from the support team says send me an pm and hes ignoring me evertime

**Comment by SocialHype** [comment]
goodjob (Y)

**Comment by parkervcp** [comment]
Just talk in the support channels. Stop PMing someone on there please. There are more support people than that.

**Comment by SocialHype** [comment]
omg this sucks if they say pm me and then they ignore you
